/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package revolut

import java.io.Console

fun main(args: Array<String>) {
    val revolutApp = RevolutApp()
    revolutApp.start(8000)
    System.console().readLine()
    revolutApp.stop()
}
